In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
from PIL import Image
%matplotlib inline

In [2]:
import pickle

In [7]:
ls data

 Volume in drive D is DATA
 Volume Serial Number is FAA9-24C8

 Directory of D:\FaceRecognition\data

19-05-2021  16:36    <DIR>          .
19-05-2021  16:36    <DIR>          ..
19-05-2021  15:34    <DIR>          crop
19-05-2021  16:36        16,707,345 dataframe_image_100x100.pickle
19-05-2021  14:59    <DIR>          men
19-05-2021  14:59    <DIR>          women
               1 File(s)     16,707,345 bytes
               5 Dir(s)  290,913,140,736 bytes free


In [8]:
df=pickle.load(open('./data/dataframe_image_100x100.pickle','rb'))

In [9]:
df.head()

gender    0    1    2    3    4    5    6    7    8  ...  9990  9991  9992  \
0  female  217  217  217  218  215  204  155  111  150  ...   102    85    80   
1  female  187  173  164  160  160  169  166  124   74  ...   103   112   121   
2  female  107  132  140  149  136  133  124  111  105  ...    94   108   106   
5  female   65   48   49   67   58   47   79   69   43  ...   104   106   114   
6  female  178  177  174  171  166  165  166  167  168  ...    61    12    27   

   9993  9994  9995  9996  9997  9998  9999  
0   108    81   124   158   171   179   194  
1   113   102    99    86    62    57    55  
2   109   105   117   113    81    76    72  
5   121   129   146   161   172   162   154  
6    30    24    22    19    21    30    32  

[5 rows x 10001 columns]

In [10]:
df.shape

(1662, 10001)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1662 entries, 0 to 1825
Columns: 10001 entries, gender to 9999
dtypes: object(1), uint8(10000)
memory usage: 15.9+ MB


In [16]:
df.isnull().sum()

gender    0
0         0
1         0
2         0
3         0
         ..
9995      0
9996      0
9997      0
9998      0
9999      0
Length: 10001, dtype: int64

In [15]:
#checking for missing values
df.isnull().sum().sum()

0

In [17]:
#hence no na values

In [18]:
# Data Normalisation
#Split the data into 2 parts
X=df.iloc[:,1:].values

In [19]:
X

array([[217, 217, 217, ..., 171, 179, 194],
       [187, 173, 164, ...,  62,  57,  55],
       [107, 132, 140, ...,  81,  76,  72],
       ...,
       [ 51,  36,  39, ..., 139, 139, 139],
       [233, 233, 233, ...,  23,  23,  29],
       [245, 245, 246, ..., 248, 248, 248]], dtype=uint8)

In [20]:
y=df.iloc[:,0].values

In [21]:
y

array(['female', 'female', 'female', ..., 'male', 'male', 'male'],
      dtype=object)

In [22]:
X.shape

(1662, 10000)

In [23]:
y.shape

(1662,)

In [30]:
#Min Max Scaling (Normalisation)
X.min(),X.max()

(0, 255)

Xnorm=X-minX/(maxX-minX) == (X-0)/(255-0) ==X/255

In [31]:
Xnorm=X/X.max()

In [32]:
Xnorm

array([[0.85098039, 0.85098039, 0.85098039, ..., 0.67058824, 0.70196078,
        0.76078431],
       [0.73333333, 0.67843137, 0.64313725, ..., 0.24313725, 0.22352941,
        0.21568627],
       [0.41960784, 0.51764706, 0.54901961, ..., 0.31764706, 0.29803922,
        0.28235294],
       ...,
       [0.2       , 0.14117647, 0.15294118, ..., 0.54509804, 0.54509804,
        0.54509804],
       [0.91372549, 0.91372549, 0.91372549, ..., 0.09019608, 0.09019608,
        0.11372549],
       [0.96078431, 0.96078431, 0.96470588, ..., 0.97254902, 0.97254902,
        0.97254902]])

In [33]:
Xnorm.shape

(1662, 10000)

In [34]:
y

array(['female', 'female', 'female', ..., 'male', 'male', 'male'],
      dtype=object)

In [35]:
#Converting string to numbers
# female=1, male =0

In [37]:
y_norm=np.where(y=='female',1,0)

In [38]:
y_norm

array([1, 1, 1, ..., 0, 0, 0])

In [40]:
#Saving X and y
np.savez('./data/data_100_100',Xnorm,y_norm)